name: app_volley
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0


 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"
  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  
  assets:
    - assets/image/ball.png
    - assets/icon/icon.png
   

  fonts:
    - family: ConcertOne
      fonts:
        - asset: assets/font/ConcertOne-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
